<?php return array(
    'root' => array(
        'name' => 'neos/neos-base-distribution',
        'pretty_version' => '8.3.x-dev',
        'version' => '8.3.9999999.9999999-dev',
        'reference' => 'eb709befbd85dab93af7a9edcf0b4e6dbdb8e0dc',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'behat/transliterator' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'reference' => 'baac5873bac3749887d28ab68e2f74db3a4408af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/transliterator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.12.1',
            'version' => '0.12.1.0',
            'reference' => 'f510c0a40911935b77b86859eb5223d58d660df1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '0c5ccfcfea312b5c5a190a21ac5cef93f74baf99',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/class-map-generator' => array(
            'pretty_version' => '1.3.4',
            'version' => '1.3.4.0',
            'reference' => 'b1b3fd0b4eaf3ddf3ee230bc340bf3fff454a1a3',
            'type' => 'library',
            'install_path' => __DIR__ . '/./class-map-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/composer' => array(
            'pretty_version' => '2.7.7',
            'version' => '2.7.7.0',
            'reference' => '291942978f39435cf904d33739f98d7d4eca7b23',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/metadata-minifier' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'c549d23829536f0d0e984aaabbf02af91f443207',
            'type' => 'library',
            'install_path' => __DIR__ . '/./metadata-minifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.1.4',
            'version' => '3.1.4.0',
            'reference' => '04229f163664973f68f38f6f73d917799168ef24',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => '35e8d0af4486141bc745f23a29cc2091eb624a32',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.8',
            'version' => '1.5.8.0',
            'reference' => '560bdcf8deb88ae5d611c80a2de8ea9d0358cc0a',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '3.0.5',
            'version' => '3.0.5.0',
            'reference' => '6c1925561632e83d60a44492e0b344cf48ab85ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.14.3',
            'version' => '1.14.3.0',
            'reference' => 'fb0d71a7393298a7b232cbf4c8b1f73f3ec3d5af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1ca8f21980e770095a31456042471a57bc4c68fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '2.2.2',
            'version' => '2.2.2.0',
            'reference' => 'd8af7f248c74f195f7347424600fd9e17b57af59',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '3.4.4',
            'version' => '3.4.4.0',
            'reference' => '0aad4b7ab7ce8c6602dfbb1e1a24581275fb9d1a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.13.9',
            'version' => '2.13.9.0',
            'reference' => 'c480849ca3ad6706a39c970cdfe6888fa8a058b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'dfbaa3c2d2e9a9df1118213f3b8b0c597bb99fab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '95aa4cb529f1e96576f3fda9f5705ada4056a520',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.10',
            'version' => '2.0.10.0',
            'reference' => '5817d0659c5b50c9b950feb9af7b9668e2c436bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'c6222283fa3f4ac679f8b9ced9a4e23f163e80d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '861c870e8b75f7c8f69c146c7f89cc1c0f1b49b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/migrations' => array(
            'pretty_version' => '3.4.3',
            'version' => '3.4.3.0',
            'reference' => '362f07ff732a2b4498be919561536800cec29500',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/migrations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/orm' => array(
            'pretty_version' => '2.19.5',
            'version' => '2.19.5.0',
            'reference' => '94986af28452da42a46a4489d1c958a2e5d710e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/orm',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '3.3.3',
            'version' => '3.3.3.0',
            'reference' => 'b337726451f5d530df338fc7f68dee8781b49779',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '3.2.6',
            'version' => '3.2.6.0',
            'reference' => 'e5997fa97e8790cdae03a9cbd5e78e45e3c7bda7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'enshrined/svg-sanitize' => array(
            'pretty_version' => '0.17.0',
            'version' => '0.17.0.0',
            'reference' => 'a1af5cd21636306414da3f6ad4707b98c7601582',
            'type' => 'library',
            'install_path' => __DIR__ . '/../enshrined/svg-sanitize',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'flowpack/behat' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '8.3.0',
            ),
        ),
        'friendsofphp/proxy-manager-lts' => array(
            'pretty_version' => 'v1.0.18',
            'version' => '1.0.18.0',
            'reference' => '2c8a6cffc3220e99352ad958fe7cf06bf6f7690f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../friendsofphp/proxy-manager-lts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'gedmo/doctrine-extensions' => array(
            'pretty_version' => 'v3.13.0',
            'version' => '3.13.0.0',
            'reference' => '291d0c527d2dc9ee07b888c9a4e2a179893f08ab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gedmo/doctrine-extensions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.8.1',
            'version' => '7.8.1.0',
            'reference' => '41042bc7ab002487b876a0683fc8dce04ddce104',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'bbff78d96034045e58e13dedd6ad91b5d1253223',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.6.2',
            'version' => '2.6.2.0',
            'reference' => '45b30f99ac27b5ca93cb4831afe16285f57b8221',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'imagine/imagine' => array(
            'pretty_version' => '1.3.5',
            'version' => '1.3.5.0',
            'reference' => '7151d553edec4dc2bbac60419f7a74ff34700e7f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../imagine/imagine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => 'v5.2.13',
            'version' => '5.2.13.0',
            'reference' => 'fbbe7e5d79f618997bc3332a6f49246036c45793',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-code' => array(
            'pretty_version' => '4.14.0',
            'version' => '4.14.0.0',
            'reference' => '562e02b7d85cb9142b5116cc76c4c7c162a11a1c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/csv' => array(
            'pretty_version' => '9.16.0',
            'version' => '9.16.0.0',
            'reference' => '998280c6c34bd67d8125fdc8b45bae28d761b440',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/csv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.9.0',
            'version' => '2.9.0.0',
            'reference' => 'f5ac2c0b0a2eefca70b2ce32a5809992227e75a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikey179/vfsstream' => array(
            'pretty_version' => 'v1.6.11',
            'version' => '1.6.11.0',
            'reference' => '17d16a85e6c26ce1f3e2fa9ceeacdc2855db1e9f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikey179/vfsstream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '3a6b9a42cd8f8771bd4295d13e1423fa7f3d942c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'neos/behat' => array(
            'pretty_version' => '8.3.0',
            'version' => '8.3.0.0',
            'reference' => 'ac654fb460d31e148df79e19a159ade864d50f4d',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Behat',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'neos/buildessentials' => array(
            'pretty_version' => '8.3.0',
            'version' => '8.3.0.0',
            'reference' => '5447dd56e6bb2eae40a47687ce384905edb9c92a',
            'type' => 'neos-build',
            'install_path' => __DIR__ . '/../../../Build/BuildEssentials',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'neos/cache' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '26d8c923431575c33c123e6995afa8c29d457129',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/cli-setup' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'neos/composer-plugin' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'reference' => '6f148a5c61bb9b5f03f064c1f74829381c3fdaca',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../neos/composer-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/content-repository' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => '919d43f09e16a29ed0fe64ab7b0ac7056e8d9318',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.ContentRepository',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/demo' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => '97e3c7fd78282842fe57f96d30c0a0a3579bc722',
            'type' => 'neos-site',
            'install_path' => __DIR__ . '/../../Sites/Neos.Demo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/diff' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => 'c4c28a815ffee57f81d1a6aff2927612d1874106',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Diff',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/eel' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => 'ec1a3d4b401d70e8833d8032e52a6744ae993010',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.Eel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/error-messages' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '65a7db8b29d7a66e88fa2b11fb56ee00dfa97dc1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/error-messages',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/flow' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '6dcf104af331c18c667626245182c2ff66e56c76',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.Flow',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/flow-log' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '44f0ec3a145b7b402e01b3826607bc5576a1e33b',
            'type' => 'package',
            'install_path' => __DIR__ . '/../neos/flow-log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/fluid-adaptor' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '205381d36d697bbba6c7919a40c1d2f2d6f1dd3b',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.FluidAdaptor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/fusion' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => '4aecc7a5f4054444c4b35a0411a270de7e9d6841',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Fusion',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/fusion-afx' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => '0491efdd6a75bcaf57c35cd171f3d27ace4751a5',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Fusion.Afx',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/fusion-form' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '75e08003fd1d0fa2236dea719f0528bd3ed63483',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Fusion.Form',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/http-factories' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => 'acb8cb044b756696fd5733b461b19a5de63c52c0',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.Http.Factories',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/imagine' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => '496424c31e0fc7b6fbdc0bb5bc5d4dbc0755d75a',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Imagine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/kickstarter' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '1776924fcf79ead6a402dc374d2629562ac4e07f',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.Kickstarter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/media' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => 'bb439d81defeb8ca9c68baf3b79f60417c086205',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Media',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/media-browser' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => 'c20119050053de06d3d89192328fc262f50f9e20',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Media.Browser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => 'f93fa9f86ca6d8498efd371660120868d51ac438',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Neos',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos-base-distribution' => array(
            'pretty_version' => '8.3.x-dev',
            'version' => '8.3.9999999.9999999-dev',
            'reference' => 'eb709befbd85dab93af7a9edcf0b4e6dbdb8e0dc',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos-setup' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '63417aa6cd17351609d982f1f20befd67f425d0c',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Neos.Setup',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos-ui' => array(
            'pretty_version' => '8.3.8',
            'version' => '8.3.8.0',
            'reference' => 'd243a1ae82f38c5edb8ea007dfc4b34c78b16da8',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Neos.Ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos-ui-compiled' => array(
            'pretty_version' => '8.3.8',
            'version' => '8.3.8.0',
            'reference' => 'c71fbf3d1684c6f7140efd8d1a3e9b8f5cb99a46',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Neos.Ui.Compiled',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-assetlist' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => '103a34ca8060ec89e27e6875aefc96c05da7e1bc',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.AssetList',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-basemixins' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => '98281496046ae2ed0485708263822fc25fc612a9',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.BaseMixins',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-contentreferences' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => 'f2359a2fb5ab11af91ad3c3b2a2898e443d158ee',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.ContentReferences',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-html' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => '15eebb6687391f2ccbdafb80767bb46896f6a08b',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.Html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-navigation' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => 'efabafd3b579d984007aae6a1db851faa10fb0f7',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.Navigation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/party' => array(
            'pretty_version' => '7.0.4',
            'version' => '7.0.4.0',
            'reference' => 'cbb916b22ee992671938be5fcfe3bdc22b0a3e42',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Party',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/redirecthandler' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => 'fa24ecd1b951d0c8e388027f5f459f89a0e29230',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.RedirectHandler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/redirecthandler-databasestorage' => array(
            'pretty_version' => '5.0.4',
            'version' => '5.0.4.0',
            'reference' => 'ae54f94690f6b836be48fac8824afb00f8a3f5ee',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.RedirectHandler.DatabaseStorage',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/redirecthandler-neosadapter' => array(
            'pretty_version' => '4.3.4',
            'version' => '4.3.4.0',
            'reference' => '221b672b38e5ccc7bab0533dd52281cb3fe146fd',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.RedirectHandler.NeosAdapter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/redirecthandler-storageimplementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '3.0',
            ),
        ),
        'neos/redirecthandler-ui' => array(
            'pretty_version' => '2.5.1',
            'version' => '2.5.1.0',
            'reference' => '45a5b9e3a2d5bfd516d7c7be61dfc8d8a1fc6e6f',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.RedirectHandler.Ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/seo' => array(
            'pretty_version' => '3.3.5',
            'version' => '3.3.5.0',
            'reference' => '0af7cf29dcdfb5cde9566df5b54b5875760a266a',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Seo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/setup' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => 'ecd193d814aea502aad71b0907f193de08fc9d0d',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Setup',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/site-kickstarter' => array(
            'pretty_version' => '8.3.15',
            'version' => '8.3.15.0',
            'reference' => 'ba9b8771847be35c6ebbbead1eec6513b2b3d564',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.SiteKickstarter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/twitter-bootstrap' => array(
            'pretty_version' => '3.0.8',
            'version' => '3.0.8.0',
            'reference' => '188c91ff0e504bb367526aff0275d5d13e0e37bf',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Twitter.Bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-arrays' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => 'd0adc6cdf5d1b576035160b2200343859ba733f8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-arrays',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-files' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => 'eb80af072d3effdbbf8c9ed51240f3d28deedec9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-files',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-mediatypes' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '0e27524e3f619574b1f9d00c15302c4e006a0cdc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-mediatypes',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-objecthandling' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => 'bf6ea4cfe8f0b3b907ae12651f28f94832ab3f32',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-objecthandling',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-opcodecache' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '8e2600145eec2d2c5e7c82f458172bd874ef520c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-opcodecache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-pdo' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '11b5bc1490348baf24be34b70958bce77191ba7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-pdo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-schema' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '21f653a863448cbc0e3bd354a5700bcc07fa681f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-unicode' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => '6dd94e5d1b8c87bdfdfb3fb4a930482fc43f8429',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-unicode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v5.0.2',
            'version' => '5.0.2.0',
            'reference' => '139676794dc1e9231bf7bcd123cfc0c99182cb13',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'ocramius/proxy-manager' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.1',
            ),
        ),
        'packagefactory/atomicfusion-afx' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '54750ef60c58e43759730615a392c31c80e23176',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.31',
            'version' => '9.2.31.0',
            'reference' => '48c34b5d8d983006bd2adc2d0de92963b9155965',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.6',
            'version' => '3.0.6.0',
            'reference' => 'cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.6.19',
            'version' => '9.6.19.0',
            'reference' => 'a1a54a473501ef4cdeaae4e06891674114d79db8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0.0 || 3.0.0',
                1 => '2.0|3.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-server-handler' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '84c4fb66179be4caaf8e97bd239203245302e7d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-server-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-server-middleware' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'c1481f747daaa6a0782775cd6a8c26a1bf4a3829',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-server-middleware',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'ef29f6d262798707a9edd554e2b82517ef3a9376',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
                1 => '2.0.0 || 3.0.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0.0 || 3.0.0',
                1 => '1.0|2.0|3.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.7.6',
            'version' => '4.7.6.0',
            'reference' => '91039bc1faa45ba123c4328958e620d382ec7088',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v3.2.0',
            'version' => '3.2.0.0',
            'reference' => '8a164643313c71354582dc850b42b33fa12a4b63',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.7.6',
            ),
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '2b56bea83a09de3ac06bb18b92f068e60cc6f50b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.8',
            'version' => '4.0.8.0',
            'reference' => 'fa0f136dd2334583309d32b62544682ee972b51a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '25f207c40d62b8b7aa32f5ab026c53561964053a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => 'ba01945089c3a293b01ba9badc29ad55b106b0bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.5',
            'version' => '5.1.5.0',
            'reference' => '830c43a844f1f8d5b7a1f6d6076b784454d8b7ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => '78c00df8f170e02473b682df15bfcdacc3d32d72',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.7',
            'version' => '5.0.7.0',
            'reference' => 'bca7df1f32ee6fe93b4d4a9abbf69e13a4ada2c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => 'e1e4a170560925c26d424b6a03aed157e7dcc5c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.5',
            'version' => '4.0.5.0',
            'reference' => 'e75bd0f07204fec2a0af9b0f3cfe97d05f92efc1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'reference' => '05d5692a7993ecccd56a03e40cd7e5b09b1d404e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '75e2c2a32f5e0b3aef905b9ed0b179b953b3d7c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.10.2',
            'version' => '1.10.2.0',
            'reference' => '9bb7db07b5d66d90f6ebf542f09fc67d800e5259',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'ea2f4014f163c1be4c601b9b7bd6af81ba8d701c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'seld/signal-handler' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '04a6112e883ad76c0ada8e4a9f7520bbfdb6bb98',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/signal-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '287142df5579ce223c485b3872df3efae8390984',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'df6a1a44c890faded49a5fca33c2d5c5fd3c2197',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.4.40',
            'version' => '5.4.40.0',
            'reference' => 'aa73115c0c24220b523625bfcfa655d7d73662dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => '0e0d29ce1f20deffb4ab1b016a7257c4f1e789a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '105b56a0305d219349edeb60a800082eca864e4b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v7.1.1',
            'version' => '7.1.1.0',
            'reference' => '802e87002f919296c9f606457d9fa327a0b3d6b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v7.1.1',
            'version' => '7.1.1.0',
            'reference' => 'fbb0ba67688b780efbc886c1a0a0948dcf7205d6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => '0424dff1c58f028c451efff2045f5d92410bd540',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => '64647a7c30b2283f5d49b874d84a18fc22054b7a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => 'a6e83bdeb3c84391d1dfe16f42e40727ce524a5c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => 'a95281b0be0d9ab48050ebd988b967875cdb9fdb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php70' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php71' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php72' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php73' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php74' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php80' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => '3fb075789fb91f9ad9af537c4012d523085bd5af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v7.1.1',
            'version' => '7.1.1.0',
            'reference' => 'febf90124323a093c7ee06fdb30e765ca3c20028',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'bd1d9e59a81d8fa4acdcea3f617c581f7475a80f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '63e069eb616049632cde9674c46957819454b8aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => 'a147c0f826c4a1f3afb763ab8e009e37c877a44d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v7.1.1',
            'version' => '7.1.1.0',
            'reference' => 'db82c2b73b88734557cfc30e3270d83fa651b712',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '52903de178d542850f6f341ba92995d3d63e60c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => '737eda637ed5e28c3413cb1ebe8bb52cbf1ca7a2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'typo3/imagine' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.3.2',
            ),
        ),
        'typo3/media' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.3.15',
            ),
        ),
        'typo3/neos' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.3.15',
            ),
        ),
        'typo3/neos-base-distribution' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.3.x-dev',
            ),
        ),
        'typo3/neos-kickstarter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.3.15',
            ),
        ),
        'typo3/neos-seo' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.3.5',
            ),
        ),
        'typo3/setup' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '6.0.0',
            ),
        ),
        'typo3/twitter-bootstrap' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.0.8',
            ),
        ),
        'typo3/typo3cr' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.3.15',
            ),
        ),
        'typo3/typoscript' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.3.15',
            ),
        ),
        'typo3fluid/fluid' => array(
            'pretty_version' => '2.7.4',
            'version' => '2.7.4.0',
            'reference' => '24f4494083c8d304680e4c9c38667dff33720dd4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../typo3fluid/fluid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webexcess/redirecthandler-backend' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
    ),
);
