<?php 
declare(strict_types=1);

namespace Neos\Http\Factories;

use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Message\ServerRequestFactoryInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UploadedFileFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;

class PsrHttpFactory_Original implements ServerRequestFactoryInterface, RequestFactoryInterface, ResponseFactoryInterface,
                                UriFactoryInterface, StreamFactoryInterface, UploadedFileFactoryInterface
{
    use ServerRequestFactoryTrait;
    use RequestFactoryTrait;
    use ResponseFactoryTrait;
    use UriFactoryTrait;
    use StreamFactoryTrait;
    use UploadedFileFactoryTrait;
}

#
# Start of Flow generated Proxy code
#

class PsrHttpFactory extends PsrHttpFactory_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     *
     * ServerRequestFactory constructor.
     *
     * @param UriFactoryInterface $uriFactory
     * @param string $defaultUserAgent
     * @param string $scriptPath
     * @param string $defaultHttpVersion
     */
    public function __construct()
    {
        $arguments = func_get_args();

        if (!array_key_exists(0, $arguments)) $arguments[0] = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Psr\Http\Message\UriFactoryInterface');
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $uriFactory in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        parent::__construct(...$arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'uriFactory' => 'Psr\\Http\\Message\\UriFactoryInterface',
  'defaultUserAgent' => 'string',
  'scriptPath' => 'string',
  'defaultHttpVersion' => 'string',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /var/www/neos/Packages/Framework/Neos.Http.Factories/Classes/PsrHttpFactory.php
#