<?php 

namespace Neos\Neos\Setup\Infrastructure\Healthcheck;

use Neos\Flow\Configuration\ConfigurationManager;
use Neos\Neos\Setup\Infrastructure\ImageHandler\ImageHandlerService;
use Neos\Setup\Domain\Health;
use Neos\Setup\Domain\HealthcheckEnvironment;
use Neos\Setup\Domain\HealthcheckInterface;
use Neos\Setup\Domain\Status;

class ImageHandlerHealthcheck_Original implements HealthcheckInterface
{
    public function __construct(
        private ConfigurationManager $configurationManager,
        private ImageHandlerService $imageHandlerService,
    ) {
    }

    public function getTitle(): string
    {
        return 'Image handling';
    }

    public function execute(HealthcheckEnvironment $environment): Health
    {
        $availableImageHandlers = $this->imageHandlerService->getAvailableImageHandlers();

        if (count($availableImageHandlers) === 0) {
            $enableGdOnWindowsHelpText = $environment->executionEnvironment->isWindows
                ? ' To enabled Gd for basic image driver support during development, uncomment (remove the <em>;</em>) <em>;extension=gd</em> in your php.ini.'
                : '';

            return new Health(sprintf('No supported image handler found.%s', $enableGdOnWindowsHelpText), Status::ERROR());
        }

        $configuredDriver = $this->configurationManager->getConfiguration(
            ConfigurationManager::CONFIGURATION_TYPE_SETTINGS,
            'Neos.Imagine.driver'
        );

        if (!$configuredDriver) {
            // should never happen, as it defaults to GD
            return new Health(<<<'MSG'
            No image driver in <em>Neos.Imagine.driver</em> configured. For configuration you can use <code>{{flowCommand}} setup:imagehandler</code>
            MSG, Status::ERROR());
        }

        if ($this->imageHandlerService->isDriverEnabledInConfiguration($configuredDriver) === false) {
            return new Health(sprintf('The "driver" %s for Imagine must be enabled by settings, check Neos.Imagine.enabledDrivers. Or use <code>{{flowCommand}} setup:imagehandler</code>', $configuredDriver), Status::ERROR());
        }

        $preferredImageHandler = $this->imageHandlerService->getPreferredImageHandler();

        if ($configuredDriver !== $preferredImageHandler->driverName) {
            return new Health(<<<'MSG'
            You can use a more optional image driver than in <em>Neos.Imagine.driver</em> configured. For configuration you can use <code>{{flowCommand}} setup:imagehandler</code>
            MSG, Status::WARNING());
        }

        if ($configuredDriver === 'Gd') {
            return new Health(<<<'MSG'
            Using GD in production environment is not recommended as it has some issues and can easily lead to blank pages due to memory exhaustion.
            MSG, Status::WARNING());
        }

        return new Health(<<<'MSG'
        The image driver is correctly setup
        MSG, Status::OK());
    }
}

#
# Start of Flow generated Proxy code
#

class ImageHandlerHealthcheck extends ImageHandlerHealthcheck_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        $arguments = func_get_args();

        if (!array_key_exists(0, $arguments)) $arguments[0] = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Configuration\ConfigurationManager');
        if (!array_key_exists(1, $arguments)) $arguments[1] = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Neos\Setup\Infrastructure\ImageHandler\ImageHandlerService');
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $configurationManager in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        if (!array_key_exists(1, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $imageHandlerService in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        parent::__construct(...$arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /var/www/neos/Packages/Application/Neos.Neos.Setup/Classes/Infrastructure/Healthcheck/ImageHandlerHealthcheck.php
#