<?php 
declare(strict_types=1);

namespace Neos\Neos\Domain\Service;

/*
 * This file is part of the Neos.Neos package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\ContentRepository\Domain\Model\NodeType;
use Neos\ContentRepository\Domain\Service\NodeTypeManager;
use Neos\Flow\ObjectManagement\ObjectManagerInterface;
use Neos\Flow\Package\PackageManager;
use Neos\Fusion\Core\FusionSourceCode;
use Neos\Fusion\Core\FusionSourceCodeCollection;
use Neos\Neos\Domain\Exception as NeosDomainException;
use Neos\Neos\Domain\Model\Site;
use Neos\Flow\Annotations as Flow;

class FusionSourceCodeFactory_Original
{
    #[Flow\InjectConfiguration("fusion.autoInclude")]
    protected array $autoIncludeConfiguration = [];

    #[Flow\Inject]
    protected NodeTypeManager $nodeTypeManager;

    #[Flow\Inject]
    protected PackageManager $packageManager;

    #[Flow\Inject]
    protected ObjectManagerInterface $objectManager;

    public function createFromAutoIncludes(): FusionSourceCodeCollection
    {
        $sourcecode = FusionSourceCodeCollection::empty();
        foreach (array_keys($this->packageManager->getAvailablePackages()) as $packageKey) {
            if (isset($this->autoIncludeConfiguration[$packageKey]) && $this->autoIncludeConfiguration[$packageKey] === true) {
                $sourcecode = $sourcecode->union(
                    FusionSourceCodeCollection::tryFromPackageRootFusion($packageKey)
                );
            }
        }
        return $sourcecode;
    }

    public function createFromSite(Site $site): FusionSourceCodeCollection
    {
        return FusionSourceCodeCollection::tryFromPackageRootFusion($site->getSiteResourcesPackageKey());
    }

    /**
     * Generate Fusion prototype definitions for all node types
     *
     * Only fully qualified node types (e.g. MyVendor.MyPackage:NodeType) will be considered.
     *
     * @throws NeosDomainException
     */
    public function createFromNodeTypeDefinitions(): FusionSourceCodeCollection
    {
        $fusion = [];
        foreach ($this->nodeTypeManager->getNodeTypes(false) as $nodeType) {
            $fusion[] = $this->tryCreateFromNodeTypeDefinition($nodeType);
        }
        return new FusionSourceCodeCollection(...array_filter($fusion));
    }

    /**
     * Generate a Fusion prototype definition for a given node type
     *
     * A prototype will be rendered with the generator-class defined in the
     * nodeType-configuration 'fusion.prototypeGenerator'
     *
     * @throws NeosDomainException
     */
    private function tryCreateFromNodeTypeDefinition(NodeType $nodeType): ?FusionSourceCode
    {
        $generatorClassName = $nodeType->getConfiguration('options.fusion.prototypeGenerator');
        if ($generatorClassName === null) {
            return null;
        }
        if (!class_exists($generatorClassName)) {
            throw new NeosDomainException('Fusion prototype-generator Class ' . $generatorClassName . ' does not exist');
        }
        $generator = $this->objectManager->get($generatorClassName);
        if (!$generator instanceof DefaultPrototypeGeneratorInterface) {
            throw new NeosDomainException('Fusion prototype-generator Class ' . $generatorClassName . ' does not implement interface ' . DefaultPrototypeGeneratorInterface::class);
        }
        return FusionSourceCode::fromString($generator->generate($nodeType));
    }
}

#
# Start of Flow generated Proxy code
#

class FusionSourceCodeFactory extends FusionSourceCodeFactory_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if ('Neos\Neos\Domain\Service\FusionSourceCodeFactory' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->nodeTypeManager = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\ContentRepository\Domain\Service\NodeTypeManager');
        $this->packageManager = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Package\PackageManager');
        $this->objectManager = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\ObjectManagement\ObjectManagerInterface');
        $this->autoIncludeConfiguration = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get(\Neos\Flow\Configuration\ConfigurationManager::class)->getConfiguration('Settings', 'Neos.Neos.fusion.autoInclude');
        $this->Flow_Injected_Properties = array (
  0 => 'nodeTypeManager',
  1 => 'packageManager',
  2 => 'objectManager',
  3 => 'autoIncludeConfiguration',
);
    }
}
# PathAndFilename: /var/www/neos/Packages/Application/Neos.Neos/Classes/Domain/Service/FusionSourceCodeFactory.php
#